### ISSUE TITLE
用docker起的firefox无法建立与server的链接

### ISSUE THREAD

**Issue by VoidIsVoid** [ChatGPT-Hackers/ChatGPT-API-agent#8]
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/22066703/210514001-c37c8777-4aef-441a-aa94-bcffc84529ba.png">
尝试打开了network.websocket.allowInsecureFromHTTPS依旧无果. 希望给一些排查问题的建议

**Comment by acheong08** [comment]
It works normally outside of docker. Try running without it. You might also need to set your security policy as Standard instead of Strict

**Comment by VoidIsVoid** [comment]
多谢提醒, 给docker加了privileged之后正常工作了
